#include <furi.h>
#include <gui/gui.h>
#include <gui/view.h>
#include <gui/view_dispatcher.h>
#include <gui/modules/submenu.h>
#include <input/input.h>
#include <stdlib.h>
#include <string.h>
#define CELL 4
#define COLS 32
#define ROWS 13
typedef enum { GM_MENU, GM_SNAKE, GM_PONG, GM_DODGE, GM_TETRIS } GameMode;
typedef struct { Gui* gui; ViewDispatcher* vd; Submenu* menu; View* game; GameMode mode; bool running; uint32_t score,tick; int sx[96],sy[96],slen,sdx,sdy,foodx,foody; int paddle_y,ball_x,ball_y,ball_dx,ball_dy; int player_x,rock_x,rock_y; uint16_t board[13]; int tx,ty; } GamesApp;
static void reset_game(GamesApp* a){a->score=0;a->tick=0;a->running=true;if(a->mode==GM_SNAKE){a->slen=3;a->sx[0]=10;a->sy[0]=5;a->sx[1]=9;a->sy[1]=5;a->sx[2]=8;a->sy[2]=5;a->sdx=1;a->sdy=0;a->foodx=20;a->foody=8;}else if(a->mode==GM_PONG){a->paddle_y=25;a->ball_x=64;a->ball_y=32;a->ball_dx=2;a->ball_dy=1;}else if(a->mode==GM_DODGE){a->player_x=60;a->rock_x=35;a->rock_y=12;}else{memset(a->board,0,sizeof(a->board));a->tx=4;a->ty=0;}}
static bool snake_hit(GamesApp* a,int x,int y){if(x<0||x>=COLS||y<0||y>=ROWS)return true;for(int i=0;i<a->slen;i++)if(a->sx[i]==x&&a->sy[i]==y)return true;return false;}
static void snake_step(GamesApp* a){int nx=a->sx[0]+a->sdx,ny=a->sy[0]+a->sdy;if(snake_hit(a,nx,ny)){reset_game(a);return;}for(int i=a->slen-1;i>0;i--){a->sx[i]=a->sx[i-1];a->sy[i]=a->sy[i-1];}a->sx[0]=nx;a->sy[0]=ny;if(nx==a->foodx&&ny==a->foody){if(a->slen<95)a->slen++;a->score++;do{a->foodx=rand()%COLS;a->foody=rand()%ROWS;}while(snake_hit(a,a->foodx,a->foody));}}
static void pong_step(GamesApp* a){a->ball_x+=a->ball_dx;a->ball_y+=a->ball_dy;if(a->ball_y<12||a->ball_y>61)a->ball_dy=-a->ball_dy;if(a->ball_x<7&&a->ball_y>=a->paddle_y&&a->ball_y<=a->paddle_y+15){a->ball_dx=2;a->score++;}if(a->ball_x>126)a->ball_dx=-2;if(a->ball_x<0)reset_game(a);}
static void dodge_step(GamesApp* a){a->rock_y+=3;if(a->rock_y>64){a->rock_y=12;a->rock_x=5+rand()%116;a->score++;}if(a->rock_y+7>=54&&a->rock_x<a->player_x+10&&a->rock_x+7>a->player_x)reset_game(a);}
static void tetris_step(GamesApp* a){if(a->ty<11&&!(a->board[a->ty+2]&(1u<<a->tx))&&!(a->board[a->ty+2]&(1u<<(a->tx+1))))a->ty++;else{if(a->ty<12){a->board[a->ty]|=(1u<<a->tx)|(1u<<(a->tx+1));a->board[a->ty+1]|=(1u<<a->tx)|(1u<<(a->tx+1));}a->score++;a->tx=3+rand()%4;a->ty=0;if(a->board[1]&(1u<<a->tx))reset_game(a);}}
static void draw_game(Canvas* c,void* ctx){GamesApp* a=ctx;canvas_clear(c);char b[20];snprintf(b,sizeof(b),"%lu",(unsigned long)a->score);if(a->mode==GM_SNAKE){canvas_draw_str(c,2,8,"SNAKE");canvas_draw_str(c,108,8,b);for(int i=0;i<a->slen;i++)canvas_draw_box(c,a->sx[i]*CELL,12+a->sy[i]*CELL,CELL,CELL);canvas_draw_box(c,a->foodx*CELL,12+a->foody*CELL,CELL,CELL);}else if(a->mode==GM_PONG){canvas_draw_str(c,2,8,"PONG");canvas_draw_str(c,108,8,b);canvas_draw_box(c,2,a->paddle_y,3,15);canvas_draw_disc(c,a->ball_x,a->ball_y,2);}else if(a->mode==GM_DODGE){canvas_draw_str(c,2,8,"DODGE");canvas_draw_str(c,108,8,b);canvas_draw_box(c,a->player_x,54,10,6);canvas_draw_box(c,a->rock_x,a->rock_y,7,7);}else{canvas_draw_str(c,2,8,"TETRIS");canvas_draw_str(c,108,8,b);for(int y=0;y<13;y++)for(int x=0;x<10;x++)if(a->board[y]&(1u<<x))canvas_draw_box(c,24+x*4,12+y*4,4,4);canvas_draw_box(c,24+a->tx*4,12+a->ty*4,4,4);canvas_draw_box(c,28+a->tx*4,12+a->ty*4,4,4);canvas_draw_box(c,24+a->tx*4,16+a->ty*4,4,4);canvas_draw_box(c,28+a->tx*4,16+a->ty*4,4,4);}}
static void tick_game(void* ctx){GamesApp* a=ctx;if(!a->running)return;a->tick++;if(a->mode==GM_SNAKE&&a->tick%4==0)snake_step(a);else if(a->mode==GM_PONG)pong_step(a);else if(a->mode==GM_DODGE)dodge_step(a);else if(a->mode==GM_TETRIS&&a->tick%4==0)tetris_step(a);view_invalidate(a->game);}
static bool input_game(InputEvent* e,void* ctx){GamesApp* a=ctx;if(e->type!=InputTypePress&&e->type!=InputTypeRepeat)return false;if(e->key==InputKeyBack){a->running=false;view_dispatcher_switch_to_view(a->vd,0);return true;}if(a->mode==GM_SNAKE){if(e->key==InputKeyUp&&a->sdy==0){a->sdx=0;a->sdy=-1;}else if(e->key==InputKeyDown&&a->sdy==0){a->sdx=0;a->sdy=1;}else if(e->key==InputKeyLeft&&a->sdx==0){a->sdx=-1;a->sdy=0;}else if(e->key==InputKeyRight&&a->sdx==0){a->sdx=1;a->sdy=0;}}else if(a->mode==GM_PONG){if(e->key==InputKeyUp)a->paddle_y-=4;if(e->key==InputKeyDown)a->paddle_y+=4;if(a->paddle_y<12)a->paddle_y=12;if(a->paddle_y>48)a->paddle_y=48;}else if(a->mode==GM_DODGE){if(e->key==InputKeyLeft)a->player_x-=5;if(e->key==InputKeyRight)a->player_x+=5;if(a->player_x<2)a->player_x=2;if(a->player_x>116)a->player_x=116;}else{if(e->key==InputKeyLeft&&a->tx>0)a->tx--;if(e->key==InputKeyRight&&a->tx<8)a->tx++;if(e->key==InputKeyDown)tetris_step(a);}return true;}
static void menu_cb(void* ctx,uint32_t index){GamesApp* a=ctx;a->mode=(GameMode)(index+1);reset_game(a);view_dispatcher_switch_to_view(a->vd,1);}
static bool nav_back(void* ctx){GamesApp* a=ctx;view_dispatcher_stop(a->vd);return true;}
int32_t games_app(void* p){UNUSED(p);GamesApp* a=malloc(sizeof(GamesApp));memset(a,0,sizeof(GamesApp));a->gui=furi_record_open(RECORD_GUI);a->vd=view_dispatcher_alloc();a->menu=submenu_alloc();a->game=view_alloc();submenu_set_header(a->menu,"Games");submenu_add_item(a->menu,"Snake",0,menu_cb,a);submenu_add_item(a->menu,"Pong",1,menu_cb,a);submenu_add_item(a->menu,"Dodge",2,menu_cb,a);submenu_add_item(a->menu,"Tetris",3,menu_cb,a);view_set_draw_callback(a->game,draw_game);view_set_input_callback(a->game,input_game);view_set_context(a->game,a);view_dispatcher_set_event_callback_context(a->vd,a);view_dispatcher_set_tick_event_callback(a->vd,tick_game,50);view_dispatcher_set_navigation_event_callback(a->vd,nav_back);view_dispatcher_add_view(a->vd,0,submenu_get_view(a->menu));view_dispatcher_add_view(a->vd,1,a->game);view_dispatcher_attach_to_gui(a->vd,a->gui,ViewDispatcherTypeFullscreen);view_dispatcher_switch_to_view(a->vd,0);view_dispatcher_run(a->vd);view_dispatcher_remove_view(a->vd,0);view_dispatcher_remove_view(a->vd,1);view_dispatcher_free(a->vd);view_free(a->game);submenu_free(a->menu);furi_record_close(RECORD_GUI);free(a);return 0;}
